# Generated by Django 4.2.16 on 2024-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0005_project_github_link_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fas fa-question-circle', max_length=50),
        ),
    ]
